#caminho padrão
path_default:
  /portal
# configurações de conexão ao banco de dados
connection:
  host:
  name: ..\tads.db
  user:
  pass:
  type: sqlite
  port:
# caminhos desprotegidos definidos por expressões regulares
paths_unprotected:
  - /login/
  - /portal/
  - /404found/
# caminho seguido quando é acessado um sem permissão
path_unprotected_default:
  /login-form
# caminho seguido quando é acessado um inexistente
path_not_found:
  /404found
# namespace para controladores
path_controller:
  \Ifnc\Tads\Controller\
