#Configuração de rotas
/portal:  PortalController
/portalAdm: PortalAdmController
/cadastro: CadastroController
/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController
/listar-produtos: ListarProdutosController
/listar-Estadia: ListarEstadiaController
/adicionar-produto-form:  AdicionarProdutoFormController
/adicionar-produto: AdicionarProdutoController
/apagar-produto:  ApagarProdutoController
/editar-produto-form: EditarProdutoFormController
/editar-produto:  EditarProdutoController
/404found:  path404Controller
/cadastro-cliente: CadastroClienteController
/cadastro-cliente-form: CadastroClienteFormController
/cadastro-agente: CadastroAgenteController
/cadastro-agente-form: CadastroAgenteFormController
/cadastro-Estadia: CadastroEstadiaController
/cadastro-Estadia-form: CadastroEstadiaFormController
/cadastro-Transporte: CadastroTransporteController
/cadastro-Transporte-form: CadastroTransporteFormController
/cadastro-Evento: CadastroEventoController
/cadastro-Evento-form: CadastroEventoFormController