#Configuração de rotas
/portal:  PortalController
/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController
/listar-produtos: ListarProdutosController
/adicionar-produto-form:  AdicionarProdutoFormController
/adicionar-produto: AdicionarProdutoController
/apagar-produto:  ApagarProdutoController
/editar-produto-form: EditarProdutoFormController
/editar-produto:  EditarProdutoController
/404found:  path404Controller