#Configuração de rotas
/portal:  PortalController
/portalAdm: PortalAdmController
/cadastro: CadastroController

/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController

/listar-produtos: ListarProdutosController
/listar-estadia: ListarEstadiaController
/listar-transporte: ListarTransporteController
/listar-eventos: ListarEventosController
/listar-local: ListarLocalController

/adicionar-produto-form:  AdicionarProdutoFormController
/adicionar-produto: AdicionarProdutoController

/apagar-produto:  ApagarProdutoController
/apagar-estadia: ApagarEstadiaController
/apagar-transporte: ApagarTransporteController
/apagar-evento: ApagarEventoController
/apagar-local: ApagarLocalController

/editar-produto-form: EditarProdutoFormController
/editar-produto:  EditarProdutoController

/404found:  path404Controller

/cadastro-cliente: CadastroClienteController
/cadastro-cliente-form: CadastroClienteFormController
/cadastro-agente: CadastroAgenteController
/cadastro-agente-form: CadastroAgenteFormController
/cadastro-Estadia: CadastroEstadiaController
/cadastro-Estadia-form: CadastroEstadiaFormController
/cadastro-transporte: CadastroTransporteController
/cadastro-Transporte-form: CadastroTransporteFormController
/cadastro-Evento: CadastroEventoController
/cadastro-Evento-form: CadastroEventoFormController
/cadastro-Local: CadastroLocalController
/cadastro-local-form: CadastroLocalFormController